version: '3'
services:
  rabbit:
    image: rabbitmq:3.8.5-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  api:
    image: api
    build: 
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    
    ports:
      - "8000:8000"
    command: node build/index.js
    restart: "always"
    depends_on:
      - rabbit

  workers:
    image: workers
    build: 
      context: ./workers
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 5 # number of workers for testing
    env_file:
      - ./api/.env
    environment:
      - 
      - API_HOST=http://api:8000
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbit