name: Build and Push Frontend Docker Image

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: List directory contents
        run: find .
      - name: Build and push Docker image
        run: |
          cd frontend
          docker build -t neoatom/frontend:latest . --no-cache=true --platform=linux/amd64
          docker push neoatom/frontend:latest